changelog:
  categories:
    - title: Language
      labels:
        - language
        - parser
        - lexer
        - compiler
    - title: Runtime
      labels:
        - runtime
        - server
        - auth
        - database
    - title: Tooling
      labels:
        - cli
        - docs
        - vscode
        - examples
    - title: Other Changes
      labels:
        - "*"